### ISSUE TITLE
To-Do List (Sept 23)

### ISSUE THREAD

**Issue by callumjclarke** [dmpstats/Avian_Cluster_Detection#1]
- [x] Rewrite main clustering code for SF efficiency 
- [x] Ensure metrics are bird-centric
- [x] Provide readME for output descriptors 
- [x] Add distance to nearest bird metrics 
- [x] Make the revisits calculations more efficient 
- [x] Get rid of mean locations 
- [x] Create writeup of how we calculate all variables (to check methods)
- [x] Add github issues (enhancement labels) for other topics discussed (e.g. potentially better clustering etc)
